version: '3'


volumes:
  db:

name: script

services:
  alem_script:
    container_name: script
    command: python main.py
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./db:/app/db
